[workspace]

members = [
    "attention",
    "autodiff",
    "elements",
    "interfaces",
    "tensors",
    "tokenisation",
    "neural_nets",
    "transformer",
    "config",
    "embeddings",
]

resolver = "2"
