[package]
name = "neural_nets"
version = "0.1.0"
edition = "2021"


[dependencies]
interfaces = { path = "../interfaces" }
tensors = { path = "../tensors" }
autodiff = { path = "../autodiff" }
anyhow = "1.0.86"
rand = "0.8.5"
rand_chacha = "0.3.1"
statrs = "0.16.0"
